### ISSUE TITLE
Do we want to release on tags too?

### ISSUE THREAD

**Issue by jpkrohling** [grafana/opentelemetry-collector-components#50]
I assume we'll still want to run the release workflow on tag as well?

_Originally posted by @rlankfo in https://github.com/grafana/opentelemetry-collector-components/pull/49#discussion_r1098944709_

**Comment by jpkrohling** [comment]
> Not sure -- tags are just annotations on existing commits. If we don't plan on tagging commits that exist only on specific branches, we should be fine. If we want to have tags, and if we want a special build for that, we can trigger it manually after pushing the tag. git describe should then return the proper version based on the tag.

**Comment by rlankfo** [comment]
I'm fine if we don't do this (and we can still push the tags), but w/o it I don't think we'll ever end up with a "blessed" version (e.g. v0.0.1 vs v0.0.1-SNAPSHOT-<sha1>) unless we run the workflow on the tag manually as you suggested.
